<?php
require_once('../TCPDF-main/tcpdf.php');
require_once('../db.php');

$pdf = new TCPDF();
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Joyland Church');
$pdf->SetTitle('Donations Report');
$pdf->SetHeaderData('', 0, 'Donations Report', 'Generated by Joyland Church');

$pdf->AddPage();
$pdf->SetFont('helvetica', '', 12);

$html = '<h2>Donations Report</h2>';
$html .= '<table border="1" cellpadding="5">
            <tr>
                <th>Name</th>
                <th>Amount</th>
                <th>Date</th>
            </tr>';

$query = "SELECT name, amount, donation_date FROM donations ORDER BY donation_date DESC";
$result = mysqli_query($conn, $query);

while ($row = mysqli_fetch_assoc($result)) {
    $html .= '<tr>
                <td>' . htmlspecialchars($row['name']) . '</td>
                <td>' . htmlspecialchars($row['amount']) . '</td>
                <td>' . htmlspecialchars($row['donation_date']) . '</td>
              </tr>';
}

$html .= '</table>';
$pdf->writeHTML($html, true, false, true, false, '');

$pdf->Output('donations_report.pdf', 'D');
?>
